<a href="https://colab.research.google.com/github/Harshal-Goswami/-THE-INFINITE-RUNNER-GAME/blob/main/PRO_C125_Project_Boilerplate_Code.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Archery-Target** is a game in which the players shoot sharp-pointed arrows at a round target having 10 rings.

<img src="https://s3-whjr-curriculum-uploads.whjr.online/4de9132a-c71d-42ce-9099-3293e8805fd9.jpg">

## RL Problem to Solve
Hit the center of the target with maximum reward

<img src="https://s3-whjr-curriculum-uploads.whjr.online/40656a8c-14e2-4dd7-9f9e-4c17669b9182.png" width=300>


Number of **State**: ?

Number of **Actions**: ?



In [2]:
#import libraries
import numpy as np

## Reward Matrix
Reward Matrix represents states as rows and actions as columns with respective awards values assigned for a given state and action pair.

In [ ]:
#Define reward matrix

## Take Action Randomly

In [ ]:
#Define shoot()

##Q-matrix

**Q-learning** is a reinforcement learning algorithm. Given the current state, it helps to find the best action to be taken by the agent.

**Q-matrix** represents reward received after a taking particular action in the current state. Initially, all the elements of the Q-matrix are zeroes.


In [3]:
#Create Q-matrix
Q_matrix = np.zeros([6,6])
print(Q_matrix)

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


##Take Action

In [ ]:
#Define take_action
gamma = 0.8

def take_action(reward_matrix):

     #Call the shoot() function to get the action
     action = get_action(current_state, reward_matrix)
     #Print the action
     print(action)
     #Get the corresponding reward using Reward matrix
     current_sa_reward = reward_matrix[current_state, action]
     #Print reward
     print(current_sa_reward)
     return action, reward
     q_sa_value = max(Q_matrix[action,])
     print(q_sa_value)

In [ ]:
#Call take_action function
take_action(current_state, rewards, gamma)
